### ISSUE TITLE
OACとの併用

### ISSUE THREAD

**Issue by tmokmss** [joe-king-sh/lambda-function-urls-with-post-put-sample#1]
素晴らしいサンプルの作成ありがとうございます！私も同様の検証をしていて気づいたことを一点共有させてくださいmm

こちら↓の記述ですが、POST/PUTの場合でも必要なのは[x-amz-content-sha256](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html)だけで、sigv4署名は不要なようです

> If you use PUT or POST methods with your Lambda function URL, your users must include the payload hash value in the x-amz-content-sha256 header when sending the request to CloudFront. Lambda doesn't support unsigned payloads.
> https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-lambda.html

このため、L@Eではbodyのハッシュ値だけ計算し、sigv4はOACで署名するのが、コード量の観点では最適かもしれません
ご参考までに、雑に検証した際のコードはこちらです https://github.com/tmokmss/lambda-function-urls-sigv4-signer-sample/commit/06208d9ab2f147ee1872426c6d2d5ed568e2378e

何か役立てば幸いですmm

**Comment by joe-king-sh** [comment]
@tmokmss 

ご指摘いただきありがとうございます！
[x-amz-content-sha256](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html)だけ計算する形で、サンプルコードとブログを修正しようと思います。

検証に使用したコードのご提供までありがとうございました！

**Comment by tmokmss** [comment]
ありがとうございます！ブログまで、非常に助かります！！
issueは適宜closeいただいて大丈夫です、よろしくお願いいたします 🫡

**Comment by joe-king-sh** [comment]
以下で対応しました。
ご指摘いただきありがとうございました🙏
https://dev.classmethod.jp/articles/cloudfront-lambda-url-with-post-put-request/
